### ISSUE TITLE
About Documentation

### ISSUE THREAD

**Issue by MaramHarsha** [CodeChefVIT/DEVSOC21-Backend#20]
Please can you provide documentation on how to implement or please can you guide me how to implement it.

**Comment by N0v0cain3** [comment]
Hey! you can look at the `Readme.md` file, which has steps to run the backend

**Comment by N0v0cain3** [comment]
Add a `.env` file with 
``` MONGO_URL=<URL>
GOOGLE_CLIENT_ID=<CLIENT ID FROM GOOGLE CREDENTIALS>
GOOGLE_CLIENT_SECRET=<CLIENT ISECRET FROM GOOGLE CREDENTIALS>
JWT_SECRET=someSecret"
REDIRECT_URL=<redirect base url for google auth>
REDIRECT_FRONTEND=<redirect base url to frontend>
EMAIL_REDIRECT=<redirect base url within email>
AWS_ACCESS_KEY_ID=<AWS IAM access key id>
AWS_SECRET_ACCESS_KEY=<AWS IAM secret key>
AWS_DEFAULT_REGION=<AWS IAM region>
SES_EMAIL=<email to be used for SES>
RECAPTCHA_SECRET=<Google Recaptcha Secret>
ADMIN_PASSWORD =<admin portal email>
ADMIN_EMAIL=<Admin portal password
AWS_S3_BUCKET=<AWS S3 Bucket name> ```

**Comment by MaramHarsha** [comment]
i have uploaded your backend in my server but when i start i can't see admin panel. https://codeapi.sabrangjklu.tech this is the website

**Comment by N0v0cain3** [comment]
This repo has the apis for the admin portal, you can find admin portal over here https://github.com/CodeChefVIT/DEVSOC21-Admin-Portal

**Comment by MaramHarsha** [comment]
Sir then how to create database. I mean Mongo URL and configure it.

**Comment by N0v0cain3** [comment]
You can use the free tier of https://www.mongodb.com/atlas/database , you will get connection url of mongodb database

**Comment by MaramHarsha** [comment]
Default password for admin panel please.
